---
abstract: 'Use PHP as a Catalyst templating system'
author:
  - "Marty O'Brien, C<< <mob at cpan.org> >>"
  - "Marty O'Brien <mob@cpan.org>"
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.59
  JSON: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Template-PHP
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Catalyst::View: 0
  Moose: 0
  PHP: 0.14
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
